name: ransomwatch

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  torsocks-job:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      torproxy:
        image: ghcr.io/thetanz/gotham/torproxy:latest
        ports:
        - 9050:9050
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: run scraper
        run: |
          python3 ransomwatch.py scrape
      - name: run parser
        run: |
          python3 ransomwatch.py parse
      - name: teamscard report
        run: |
          python3 ransomwatch.py markdown
      - name: save changes
        run: |
          git config --global user.email "theta-bot@users.noreply.github.com"
          git config --global user.name "theta-bot"
          git commit --all --message "ğšŒğš›ğš˜ğš—ğš‹ğš˜ğš" || echo "no changes to commit"
          git push
